### ISSUE TITLE
[Feature Requests] General Enhancements

### ISSUE THREAD

**Issue by King-Wedgie** [illandril/FoundryVTT-grid-labels#1]
On the chance this ever gets further developed, the ability to change the style and positioning of the labels (font, color, size, centered in grid, under/over tokens, etc.) would be nice.

**Comment by illandril** [comment]
I've added several configuration options (and several other enhancements) in v1.0.0

The one thing you called out for that I didn't do was "under/over tokens" - having the labels show under tokens would require drawing them on the canvas directly, and drawing lots of text on a canvas can cause performance issues very, very quickly.

If there are any other configuration options you'd like though that you didn't call out before and I didn't add, feel free to open another Feature Request. I'm definitely open to adding more switches (time and technical limitations permitting).
