### ISSUE TITLE
Will there be a HEX version of the grid? 

### ISSUE THREAD

**Issue by Wotn9** [illandril/FoundryVTT-grid-labels#2]
It only works for square basically. No errors in the console so I guess it was planned only for squares ?

**Comment by illandril** [comment]
Could you share some mockups/examples of how you'd like a hex grid labeled?

One of the reasons I haven't added hex grid labels yet is because I don't know what kind of labeling people who use hex grids regularly would prefer and find useful.

Since labeling hex grids is substantially more work than labeling square grids, I don't want to spend a lot of time on a solution that isn't actually beneficial.

**Comment by Wotn9** [comment]
Apologies for the late. Thanks for your reply.
If it's more work than square grids I don't want to make you lose time on that, as you said people don't really use Hex grid except on overworld travel, so I just switched to a square grid and i'm enjoying fully your module :)

**Comment by vacuumorph** [comment]
> Could you share some mockups/examples of how you'd like a hex grid labeled?
> 
> One of the reasons I haven't added hex grid labels yet is because I don't know what kind of labeling people who use hex grids regularly would prefer and find useful.
> 
> Since labeling hex grids is substantially more work than labeling square grids, I don't want to spend a lot of time on a solution that isn't actually beneficial.

Well, I will share with you what I use, and I belive the most people use when you're using hex's in the game. That's the way that Hexographer/Worldographer uses to lable their hex's, and I belive that it's the gold standard for this kind of mapping. 

Here some images with examples of this kind of lable:

![image](https://github.com/illandril/FoundryVTT-grid-labels/assets/98887955/83b2d4ac-d8fa-4c39-9392-f900ac41232b)

As you see it starts on 000.000 and goes verticaly down, increasing a number after the dot for each hex, for example: 000.001, 000.002, 000.003, ..., 000.010...

It also goes sideways, increasing a number for each colunm, for example: 001.000, 002.000, 003.000, ..., 010.000...

Heres a image of a 20x20 hex map totally blank and with the lables:
![Hex Map Blank](https://github.com/illandril/FoundryVTT-grid-labels/assets/98887955/8e9e4868-15d3-438b-bebd-64a99d737345)
